require("modes/jd-split-factory/control")
require("modes/easter-egg-surprise-2022/control")
require("modes.jd-spider-race.control")
require("modes.battlefluffy-scenario.control")
require("modes.halloween-2023.control")
