-- Alien Biomes - 0.6.1
local Data = {}

--[[
    Generated by manually adding some code in to Alien Biomes and writing the below table to the log.
    In /prototypes/biome/biomes.lua - biomes.build_tiles function():
        - At very top of function:
            local mikeTable = {}
        - When volume_to_noise_expression() is called:
            mikeTable[biome_name] = {
                "allow-trees",
                {
                    {biome.volume.temperature_min / 100, biome.volume.water_min},
                    {biome.volume.temperature_max / 100, biome.volume.water_max}
                },
                nil,
                biome.axis
            }
        - At the very end of the function:
            log(serpent.block(mikeTable))
]]
Data.GetTileData = function()
    return {
        ["frozen-snow-0"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-1"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-2"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-3"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-4"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-5"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-6"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-7"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-8"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["frozen-snow-9"] = {
            "allow-trees",
            {
                {
                    -0.5
                },
                {
                    0
                }
            }
        },
        ["mineral-aubergine-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "aubergine"
        },
        ["mineral-aubergine-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "aubergine"
        },
        ["mineral-aubergine-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.8
                }
            },
            nil,
            "aubergine"
        },
        ["mineral-aubergine-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.95
                }
            },
            nil,
            "aubergine"
        },
        ["mineral-aubergine-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "aubergine"
        },
        ["mineral-aubergine-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "aubergine"
        },
        ["mineral-aubergine-sand-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "aubergine"
        },
        ["mineral-aubergine-sand-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "aubergine"
        },
        ["mineral-aubergine-sand-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "aubergine"
        },
        ["mineral-beige-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "beige"
        },
        ["mineral-beige-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "beige"
        },
        ["mineral-beige-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.8
                }
            },
            nil,
            "beige"
        },
        ["mineral-beige-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.95
                }
            },
            nil,
            "beige"
        },
        ["mineral-beige-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "beige"
        },
        ["mineral-beige-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "beige"
        },
        ["mineral-beige-sand-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "beige"
        },
        ["mineral-beige-sand-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "beige"
        },
        ["mineral-beige-sand-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "beige"
        },
        ["mineral-black-dirt-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "black"
        },
        ["mineral-black-dirt-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "black"
        },
        ["mineral-black-dirt-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.8
                }
            },
            nil,
            "black"
        },
        ["mineral-black-dirt-4"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.95
                }
            },
            nil,
            "black"
        },
        ["mineral-black-dirt-5"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "black"
        },
        ["mineral-black-dirt-6"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "black"
        },
        ["mineral-black-sand-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            },
            nil,
            "black"
        },
        ["mineral-black-sand-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            },
            nil,
            "black"
        },
        ["mineral-black-sand-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            },
            nil,
            "black"
        },
        ["mineral-brown-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "brown"
        },
        ["mineral-brown-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "brown"
        },
        ["mineral-brown-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            },
            nil,
            "brown"
        },
        ["mineral-brown-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            },
            nil,
            "brown"
        },
        ["mineral-brown-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "brown"
        },
        ["mineral-brown-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "brown"
        },
        ["mineral-brown-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "brown"
        },
        ["mineral-brown-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "brown"
        },
        ["mineral-brown-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "brown"
        },
        ["mineral-cream-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "cream"
        },
        ["mineral-cream-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "cream"
        },
        ["mineral-cream-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.8
                }
            },
            nil,
            "cream"
        },
        ["mineral-cream-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.95
                }
            },
            nil,
            "cream"
        },
        ["mineral-cream-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "cream"
        },
        ["mineral-cream-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "cream"
        },
        ["mineral-cream-sand-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "cream"
        },
        ["mineral-cream-sand-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "cream"
        },
        ["mineral-cream-sand-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "cream"
        },
        ["mineral-dustyrose-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "dustyrose"
        },
        ["mineral-dustyrose-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "dustyrose"
        },
        ["mineral-dustyrose-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.8
                }
            },
            nil,
            "dustyrose"
        },
        ["mineral-dustyrose-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.6
                },
                {
                    0.6,
                    0.95
                }
            },
            nil,
            "dustyrose"
        },
        ["mineral-dustyrose-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "dustyrose"
        },
        ["mineral-dustyrose-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0.4
                },
                {
                    0.6,
                    0.6
                }
            },
            nil,
            "dustyrose"
        },
        ["mineral-dustyrose-sand-1"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "dustyrose"
        },
        ["mineral-dustyrose-sand-2"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "dustyrose"
        },
        ["mineral-dustyrose-sand-3"] = {
            "allow-trees",
            {
                {
                    0.3,
                    0
                },
                {
                    0.6,
                    0.4
                }
            },
            nil,
            "dustyrose"
        },
        ["mineral-grey-dirt-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "grey"
        },
        ["mineral-grey-dirt-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "grey"
        },
        ["mineral-grey-dirt-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.8
                }
            },
            nil,
            "grey"
        },
        ["mineral-grey-dirt-4"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.95
                }
            },
            nil,
            "grey"
        },
        ["mineral-grey-dirt-5"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "grey"
        },
        ["mineral-grey-dirt-6"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "grey"
        },
        ["mineral-grey-sand-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            },
            nil,
            "grey"
        },
        ["mineral-grey-sand-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            },
            nil,
            "grey"
        },
        ["mineral-grey-sand-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            },
            nil,
            "grey"
        },
        ["mineral-purple-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "purple"
        },
        ["mineral-purple-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "purple"
        },
        ["mineral-purple-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            },
            nil,
            "purple"
        },
        ["mineral-purple-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            },
            nil,
            "purple"
        },
        ["mineral-purple-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "purple"
        },
        ["mineral-purple-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "purple"
        },
        ["mineral-purple-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "purple"
        },
        ["mineral-purple-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "purple"
        },
        ["mineral-purple-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "purple"
        },
        ["mineral-red-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "red"
        },
        ["mineral-red-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "red"
        },
        ["mineral-red-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            },
            nil,
            "red"
        },
        ["mineral-red-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            },
            nil,
            "red"
        },
        ["mineral-red-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "red"
        },
        ["mineral-red-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "red"
        },
        ["mineral-red-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "red"
        },
        ["mineral-red-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "red"
        },
        ["mineral-red-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "red"
        },
        ["mineral-tan-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "tan"
        },
        ["mineral-tan-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "tan"
        },
        ["mineral-tan-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            },
            nil,
            "tan"
        },
        ["mineral-tan-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            },
            nil,
            "tan"
        },
        ["mineral-tan-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "tan"
        },
        ["mineral-tan-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "tan"
        },
        ["mineral-tan-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "tan"
        },
        ["mineral-tan-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "tan"
        },
        ["mineral-tan-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "tan"
        },
        ["mineral-violet-dirt-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "violet"
        },
        ["mineral-violet-dirt-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "violet"
        },
        ["mineral-violet-dirt-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.8
                }
            },
            nil,
            "violet"
        },
        ["mineral-violet-dirt-4"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    1,
                    0.95
                }
            },
            nil,
            "violet"
        },
        ["mineral-violet-dirt-5"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "violet"
        },
        ["mineral-violet-dirt-6"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.4
                },
                {
                    1,
                    0.6
                }
            },
            nil,
            "violet"
        },
        ["mineral-violet-sand-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "violet"
        },
        ["mineral-violet-sand-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "violet"
        },
        ["mineral-violet-sand-3"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0
                },
                {
                    1,
                    0.4
                }
            },
            nil,
            "violet"
        },
        ["mineral-white-dirt-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "white"
        },
        ["mineral-white-dirt-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "white"
        },
        ["mineral-white-dirt-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.8
                }
            },
            nil,
            "white"
        },
        ["mineral-white-dirt-4"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.3,
                    0.95
                }
            },
            nil,
            "white"
        },
        ["mineral-white-dirt-5"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "white"
        },
        ["mineral-white-dirt-6"] = {
            "allow-trees",
            {
                {
                    0,
                    0.4
                },
                {
                    0.3,
                    0.6
                }
            },
            nil,
            "white"
        },
        ["mineral-white-sand-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            },
            nil,
            "white"
        },
        ["mineral-white-sand-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            },
            nil,
            "white"
        },
        ["mineral-white-sand-3"] = {
            "allow-trees",
            {
                {
                    0,
                    0
                },
                {
                    0.3,
                    0.4
                }
            },
            nil,
            "white"
        },
        ["vegetation-blue-grass-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.2,
                    1
                }
            },
            nil,
            "blue"
        },
        ["vegetation-blue-grass-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.2,
                    1
                }
            },
            nil,
            "blue"
        },
        ["vegetation-green-grass-1"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.5,
                    1
                }
            },
            nil,
            "green"
        },
        ["vegetation-green-grass-2"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.5,
                    1
                }
            },
            nil,
            "green"
        },
        ["vegetation-green-grass-3"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.5,
                    1
                }
            },
            nil,
            "green"
        },
        ["vegetation-green-grass-4"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.5,
                    1
                }
            },
            nil,
            "green"
        },
        ["vegetation-mauve-grass-1"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.4,
                    1
                }
            },
            nil,
            "mauve"
        },
        ["vegetation-mauve-grass-2"] = {
            "allow-trees",
            {
                {
                    0.2,
                    0.6
                },
                {
                    0.4,
                    1
                }
            },
            nil,
            "mauve"
        },
        ["vegetation-olive-grass-1"] = {
            "allow-trees",
            {
                {
                    0.5,
                    0.6
                },
                {
                    0.65,
                    1
                }
            },
            nil,
            "olive"
        },
        ["vegetation-olive-grass-2"] = {
            "allow-trees",
            {
                {
                    0.5,
                    0.6
                },
                {
                    0.65,
                    1
                }
            },
            nil,
            "olive"
        },
        ["vegetation-orange-grass-1"] = {
            "allow-trees",
            {
                {
                    0.8,
                    0.6
                },
                {
                    1,
                    1
                }
            },
            nil,
            "orange"
        },
        ["vegetation-orange-grass-2"] = {
            "allow-trees",
            {
                {
                    0.8,
                    0.6
                },
                {
                    1,
                    1
                }
            },
            nil,
            "orange"
        },
        ["vegetation-purple-grass-1"] = {
            "allow-trees",
            {
                {
                    0.4,
                    0.6
                },
                {
                    0.6,
                    1
                }
            },
            nil,
            "purple"
        },
        ["vegetation-purple-grass-2"] = {
            "allow-trees",
            {
                {
                    0.4,
                    0.6
                },
                {
                    0.6,
                    1
                }
            },
            nil,
            "purple"
        },
        ["vegetation-red-grass-1"] = {
            "allow-trees",
            {
                {
                    0.8,
                    0.6
                },
                {
                    1,
                    1
                }
            },
            nil,
            "red"
        },
        ["vegetation-red-grass-2"] = {
            "allow-trees",
            {
                {
                    0.8,
                    0.6
                },
                {
                    1,
                    1
                }
            },
            nil,
            "red"
        },
        ["vegetation-turquoise-grass-1"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.2,
                    1
                }
            },
            nil,
            "turquoise"
        },
        ["vegetation-turquoise-grass-2"] = {
            "allow-trees",
            {
                {
                    0,
                    0.6
                },
                {
                    0.2,
                    1
                }
            },
            nil,
            "turquoise"
        },
        ["vegetation-violet-grass-1"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    0.8,
                    1
                }
            },
            nil,
            "violet"
        },
        ["vegetation-violet-grass-2"] = {
            "allow-trees",
            {
                {
                    0.6,
                    0.6
                },
                {
                    0.8,
                    1
                }
            },
            nil,
            "violet"
        },
        ["vegetation-yellow-grass-1"] = {
            "allow-trees",
            {
                {
                    0.65,
                    0.6
                },
                {
                    0.8,
                    1
                }
            },
            nil,
            "yellow"
        },
        ["vegetation-yellow-grass-2"] = {
            "allow-trees",
            {
                {
                    0.65,
                    0.6
                },
                {
                    0.8,
                    1
                }
            },
            nil,
            "yellow"
        },
        ["volcanic-blue-heat-1"] = {
            "allow-trees",
            {
                {
                    1
                },
                {
                    1.2
                }
            },
            nil,
            "blue"
        },
        ["volcanic-blue-heat-2"] = {
            "allow-trees",
            {
                {
                    1.2
                },
                {
                    1.3500000000000001
                }
            },
            nil,
            "blue"
        },
        ["volcanic-blue-heat-3"] = {
            "allow-trees",
            {
                {
                    1.3500000000000001
                },
                {
                    1.45
                }
            },
            nil,
            "blue"
        },
        ["volcanic-blue-heat-4"] = {
            "allow-trees",
            {
                {
                    1.45
                },
                {
                    1.5
                }
            },
            nil,
            "blue"
        },
        ["volcanic-green-heat-1"] = {
            "allow-trees",
            {
                {
                    1
                },
                {
                    1.2
                }
            },
            nil,
            "green"
        },
        ["volcanic-green-heat-2"] = {
            "allow-trees",
            {
                {
                    1.2
                },
                {
                    1.3500000000000001
                }
            },
            nil,
            "green"
        },
        ["volcanic-green-heat-3"] = {
            "allow-trees",
            {
                {
                    1.3500000000000001
                },
                {
                    1.45
                }
            },
            nil,
            "green"
        },
        ["volcanic-green-heat-4"] = {
            "allow-trees",
            {
                {
                    1.45
                },
                {
                    1.5
                }
            },
            nil,
            "green"
        },
        ["volcanic-orange-heat-1"] = {
            "allow-trees",
            {
                {
                    1
                },
                {
                    1.2
                }
            },
            nil,
            "orange"
        },
        ["volcanic-orange-heat-2"] = {
            "allow-trees",
            {
                {
                    1.2
                },
                {
                    1.3500000000000001
                }
            },
            nil,
            "orange"
        },
        ["volcanic-orange-heat-3"] = {
            "allow-trees",
            {
                {
                    1.3500000000000001
                },
                {
                    1.45
                }
            },
            nil,
            "orange"
        },
        ["volcanic-orange-heat-4"] = {
            "allow-trees",
            {
                {
                    1.45
                },
                {
                    1.5
                }
            },
            nil,
            "orange"
        },
        ["volcanic-purple-heat-1"] = {
            "allow-trees",
            {
                {
                    1
                },
                {
                    1.2
                }
            },
            nil,
            "purple"
        },
        ["volcanic-purple-heat-2"] = {
            "allow-trees",
            {
                {
                    1.2
                },
                {
                    1.3500000000000001
                }
            },
            nil,
            "purple"
        },
        ["volcanic-purple-heat-3"] = {
            "allow-trees",
            {
                {
                    1.3500000000000001
                },
                {
                    1.45
                }
            },
            nil,
            "purple"
        },
        ["volcanic-purple-heat-4"] = {
            "allow-trees",
            {
                {
                    1.45
                },
                {
                    1.5
                }
            },
            nil,
            "purple"
        }
    }
end

--[[
    Generated by manually adding some code in to Alien Biomes and writing the below table to the log.
    In /prototypes/entity/trees.lua - very end of file:
        local mikeData = {}
        for _, tree in pairs(trees_data) do
            local tags, tileRestrictions
            if tree.tags ~= nil then
                tags = {}
                for _, tag in pairs(tree.tags) do
                    tags[tag] = tag
                end
            end
            if tree.tile_restriction ~= nil then
                tileRestrictions = {}
                for _, tileRestriction in pairs(tree.tile_restriction) do
                    tileRestrictions[tileRestriction] = tileRestriction
                end
            end
            mikeData[tree.name] = {tags, tileRestrictions}
        end
        log(serpent.block(mikeData))
]]
Data.GetTreeMetaData = function()
    return {
        ["tree-desert-a"] = {
            {
                green = "green"
            }
        },
        ["tree-desert-b"] = {
            {
                red = "red",
                violet = "violet"
            }
        },
        ["tree-desert-c"] = {
            {
                red = "red",
                yellow = "yellow"
            }
        },
        ["tree-desert-d"] = {
            {
                green = "green"
            }
        },
        ["tree-desert-e"] = {
            {
                green = "green"
            }
        },
        ["tree-desert-f"] = {
            {
                yellow = "yellow"
            }
        },
        ["tree-desert-g"] = {
            {
                green = "green"
            }
        },
        ["tree-desert-h"] = {
            {
                red = "red"
            }
        },
        ["tree-desert-i"] = {
            {
                white = "white",
                yellow = "yellow"
            }
        },
        ["tree-desert-j"] = {
            {
                red = "red",
                violet = "violet",
                white = "white"
            }
        },
        ["tree-desert-k"] = {
            {
                red = "red",
                yellow = "yellow"
            }
        },
        ["tree-desert-l"] = {
            {
                red = "red",
                violet = "violet"
            }
        },
        ["tree-desert-m"] = {
            {
                purple = "purple",
                turquoise = "turquoise"
            }
        },
        ["tree-desert-n"] = {
            {
                blue = "blue",
                purple = "purple",
                violet = "violet",
                white = "white"
            }
        },
        ["tree-dryland-a"] = {
            {
                red = "red",
                yellow = "yellow"
            }
        },
        ["tree-dryland-b"] = {
            {
                green = "green"
            }
        },
        ["tree-dryland-c"] = {
            {
                red = "red",
                violet = "violet",
                white = "white"
            }
        },
        ["tree-dryland-d"] = {
            {
                blue = "blue",
                purple = "purple",
                red = "red"
            }
        },
        ["tree-dryland-e"] = {
            {
                green = "green",
                turquoise = "turquoise"
            }
        },
        ["tree-dryland-f"] = {
            {
                green = "green",
                yellow = "yellow"
            }
        },
        ["tree-dryland-g"] = {
            {
                green = "green",
                yellow = "yellow"
            }
        },
        ["tree-dryland-h"] = {
            {
                purple = "purple",
                red = "red",
                yellow = "yellow"
            }
        },
        ["tree-dryland-i"] = {
            {
                violet = "violet"
            }
        },
        ["tree-dryland-j"] = {
            {
                green = "green",
                turquoise = "turquoise"
            }
        },
        ["tree-dryland-k"] = {
            {
                blue = "blue",
                green = "green",
                turquoise = "turquoise"
            }
        },
        ["tree-dryland-l"] = {
            {
                green = "green",
                red = "red",
                turquoise = "turquoise"
            }
        },
        ["tree-dryland-m"] = {
            {
                purple = "purple",
                violet = "violet"
            }
        },
        ["tree-dryland-n"] = {
            {
                turquoise = "turquoise"
            }
        },
        ["tree-dryland-o"] = {
            {
                purple = "purple",
                white = "white"
            }
        },
        ["tree-grassland-a"] = {
            {
                green = "green"
            }
        },
        ["tree-grassland-b"] = {
            {
                red = "red",
                yellow = "yellow"
            }
        },
        ["tree-grassland-c"] = {
            {
                red = "red",
                yellow = "yellow"
            }
        },
        ["tree-grassland-d"] = {
            {
                purple = "purple",
                red = "red"
            }
        },
        ["tree-grassland-e"] = {
            {
                purple = "purple"
            }
        },
        ["tree-grassland-f"] = {
            {
                yellow = "yellow"
            }
        },
        ["tree-grassland-g"] = {
            {
                green = "green",
                yellow = "yellow"
            }
        },
        ["tree-grassland-h"] = {
            {
                green = "green"
            }
        },
        ["tree-grassland-h2"] = {
            {
                purple = "purple",
                violet = "violet"
            }
        },
        ["tree-grassland-h3"] = {
            {
                blue = "blue",
                purple = "purple"
            }
        },
        ["tree-grassland-i"] = {
            {
                violet = "violet",
                white = "white"
            }
        },
        ["tree-grassland-j"] = {
            {
                green = "green"
            }
        },
        ["tree-grassland-k"] = {
            {
                green = "green"
            }
        },
        ["tree-grassland-l"] = {
            {
                red = "red"
            }
        },
        ["tree-grassland-m"] = {
            {
                blue = "blue",
                violet = "violet",
                white = "white"
            }
        },
        ["tree-grassland-n"] = {
            {
                blue = "blue",
                red = "red",
                white = "white"
            }
        },
        ["tree-grassland-o"] = {
            {
                turquoise = "turquoise"
            }
        },
        ["tree-grassland-p"] = {
            {
                blue = "blue",
                turquoise = "turquoise"
            }
        },
        ["tree-grassland-q"] = {
            {
                blue = "blue",
                white = "white"
            }
        },
        ["tree-palm-a"] = {
            {
                green = "green"
            },
            {
                ["mineral-aubergine-sand-1"] = "mineral-aubergine-sand-1",
                ["mineral-aubergine-sand-2"] = "mineral-aubergine-sand-2",
                ["mineral-aubergine-sand-3"] = "mineral-aubergine-sand-3",
                ["mineral-beige-sand-1"] = "mineral-beige-sand-1",
                ["mineral-beige-sand-2"] = "mineral-beige-sand-2",
                ["mineral-beige-sand-3"] = "mineral-beige-sand-3",
                ["mineral-black-sand-1"] = "mineral-black-sand-1",
                ["mineral-black-sand-2"] = "mineral-black-sand-2",
                ["mineral-black-sand-3"] = "mineral-black-sand-3",
                ["mineral-brown-sand-1"] = "mineral-brown-sand-1",
                ["mineral-brown-sand-2"] = "mineral-brown-sand-2",
                ["mineral-brown-sand-3"] = "mineral-brown-sand-3",
                ["mineral-cream-sand-1"] = "mineral-cream-sand-1",
                ["mineral-cream-sand-2"] = "mineral-cream-sand-2",
                ["mineral-cream-sand-3"] = "mineral-cream-sand-3",
                ["mineral-dustyrose-sand-1"] = "mineral-dustyrose-sand-1",
                ["mineral-dustyrose-sand-2"] = "mineral-dustyrose-sand-2",
                ["mineral-dustyrose-sand-3"] = "mineral-dustyrose-sand-3",
                ["mineral-grey-sand-1"] = "mineral-grey-sand-1",
                ["mineral-grey-sand-2"] = "mineral-grey-sand-2",
                ["mineral-grey-sand-3"] = "mineral-grey-sand-3",
                ["mineral-purple-sand-1"] = "mineral-purple-sand-1",
                ["mineral-purple-sand-2"] = "mineral-purple-sand-2",
                ["mineral-purple-sand-3"] = "mineral-purple-sand-3",
                ["mineral-red-sand-1"] = "mineral-red-sand-1",
                ["mineral-red-sand-2"] = "mineral-red-sand-2",
                ["mineral-red-sand-3"] = "mineral-red-sand-3",
                ["mineral-tan-sand-1"] = "mineral-tan-sand-1",
                ["mineral-tan-sand-2"] = "mineral-tan-sand-2",
                ["mineral-tan-sand-3"] = "mineral-tan-sand-3",
                ["mineral-violet-sand-1"] = "mineral-violet-sand-1",
                ["mineral-violet-sand-2"] = "mineral-violet-sand-2",
                ["mineral-violet-sand-3"] = "mineral-violet-sand-3",
                ["mineral-white-sand-1"] = "mineral-white-sand-1",
                ["mineral-white-sand-2"] = "mineral-white-sand-2",
                ["mineral-white-sand-3"] = "mineral-white-sand-3"
            }
        },
        ["tree-palm-b"] = {
            {
                violet = "violet"
            },
            {
                ["mineral-aubergine-sand-1"] = "mineral-aubergine-sand-1",
                ["mineral-aubergine-sand-2"] = "mineral-aubergine-sand-2",
                ["mineral-aubergine-sand-3"] = "mineral-aubergine-sand-3",
                ["mineral-beige-sand-1"] = "mineral-beige-sand-1",
                ["mineral-beige-sand-2"] = "mineral-beige-sand-2",
                ["mineral-beige-sand-3"] = "mineral-beige-sand-3",
                ["mineral-black-sand-1"] = "mineral-black-sand-1",
                ["mineral-black-sand-2"] = "mineral-black-sand-2",
                ["mineral-black-sand-3"] = "mineral-black-sand-3",
                ["mineral-brown-sand-1"] = "mineral-brown-sand-1",
                ["mineral-brown-sand-2"] = "mineral-brown-sand-2",
                ["mineral-brown-sand-3"] = "mineral-brown-sand-3",
                ["mineral-cream-sand-1"] = "mineral-cream-sand-1",
                ["mineral-cream-sand-2"] = "mineral-cream-sand-2",
                ["mineral-cream-sand-3"] = "mineral-cream-sand-3",
                ["mineral-dustyrose-sand-1"] = "mineral-dustyrose-sand-1",
                ["mineral-dustyrose-sand-2"] = "mineral-dustyrose-sand-2",
                ["mineral-dustyrose-sand-3"] = "mineral-dustyrose-sand-3",
                ["mineral-grey-sand-1"] = "mineral-grey-sand-1",
                ["mineral-grey-sand-2"] = "mineral-grey-sand-2",
                ["mineral-grey-sand-3"] = "mineral-grey-sand-3",
                ["mineral-purple-sand-1"] = "mineral-purple-sand-1",
                ["mineral-purple-sand-2"] = "mineral-purple-sand-2",
                ["mineral-purple-sand-3"] = "mineral-purple-sand-3",
                ["mineral-red-sand-1"] = "mineral-red-sand-1",
                ["mineral-red-sand-2"] = "mineral-red-sand-2",
                ["mineral-red-sand-3"] = "mineral-red-sand-3",
                ["mineral-tan-sand-1"] = "mineral-tan-sand-1",
                ["mineral-tan-sand-2"] = "mineral-tan-sand-2",
                ["mineral-tan-sand-3"] = "mineral-tan-sand-3",
                ["mineral-violet-sand-1"] = "mineral-violet-sand-1",
                ["mineral-violet-sand-2"] = "mineral-violet-sand-2",
                ["mineral-violet-sand-3"] = "mineral-violet-sand-3",
                ["mineral-white-sand-1"] = "mineral-white-sand-1",
                ["mineral-white-sand-2"] = "mineral-white-sand-2",
                ["mineral-white-sand-3"] = "mineral-white-sand-3"
            }
        },
        ["tree-snow-a"] = {
            {
                green = "green",
                turquoise = "turquoise",
                white = "white"
            },
            {
                ["frozen-snow-0"] = "frozen-snow-0",
                ["frozen-snow-1"] = "frozen-snow-1",
                ["frozen-snow-2"] = "frozen-snow-2",
                ["frozen-snow-3"] = "frozen-snow-3",
                ["frozen-snow-4"] = "frozen-snow-4",
                ["mineral-aubergine-dirt-1"] = "mineral-aubergine-dirt-1",
                ["mineral-aubergine-dirt-2"] = "mineral-aubergine-dirt-2",
                ["mineral-aubergine-dirt-3"] = "mineral-aubergine-dirt-3",
                ["mineral-aubergine-dirt-4"] = "mineral-aubergine-dirt-4",
                ["mineral-aubergine-dirt-5"] = "mineral-aubergine-dirt-5",
                ["mineral-aubergine-dirt-6"] = "mineral-aubergine-dirt-6",
                ["mineral-aubergine-sand-1"] = "mineral-aubergine-sand-1",
                ["mineral-aubergine-sand-2"] = "mineral-aubergine-sand-2",
                ["mineral-aubergine-sand-3"] = "mineral-aubergine-sand-3",
                ["mineral-beige-dirt-1"] = "mineral-beige-dirt-1",
                ["mineral-beige-dirt-2"] = "mineral-beige-dirt-2",
                ["mineral-beige-dirt-3"] = "mineral-beige-dirt-3",
                ["mineral-beige-dirt-4"] = "mineral-beige-dirt-4",
                ["mineral-beige-dirt-5"] = "mineral-beige-dirt-5",
                ["mineral-beige-dirt-6"] = "mineral-beige-dirt-6",
                ["mineral-beige-sand-1"] = "mineral-beige-sand-1",
                ["mineral-beige-sand-2"] = "mineral-beige-sand-2",
                ["mineral-beige-sand-3"] = "mineral-beige-sand-3",
                ["mineral-black-dirt-1"] = "mineral-black-dirt-1",
                ["mineral-black-dirt-2"] = "mineral-black-dirt-2",
                ["mineral-black-dirt-3"] = "mineral-black-dirt-3",
                ["mineral-black-dirt-4"] = "mineral-black-dirt-4",
                ["mineral-black-dirt-5"] = "mineral-black-dirt-5",
                ["mineral-black-dirt-6"] = "mineral-black-dirt-6",
                ["mineral-black-sand-1"] = "mineral-black-sand-1",
                ["mineral-black-sand-2"] = "mineral-black-sand-2",
                ["mineral-black-sand-3"] = "mineral-black-sand-3",
                ["mineral-brown-dirt-1"] = "mineral-brown-dirt-1",
                ["mineral-brown-dirt-2"] = "mineral-brown-dirt-2",
                ["mineral-brown-dirt-3"] = "mineral-brown-dirt-3",
                ["mineral-brown-dirt-4"] = "mineral-brown-dirt-4",
                ["mineral-brown-dirt-5"] = "mineral-brown-dirt-5",
                ["mineral-brown-dirt-6"] = "mineral-brown-dirt-6",
                ["mineral-brown-sand-1"] = "mineral-brown-sand-1",
                ["mineral-brown-sand-2"] = "mineral-brown-sand-2",
                ["mineral-brown-sand-3"] = "mineral-brown-sand-3",
                ["mineral-cream-dirt-1"] = "mineral-cream-dirt-1",
                ["mineral-cream-dirt-2"] = "mineral-cream-dirt-2",
                ["mineral-cream-dirt-3"] = "mineral-cream-dirt-3",
                ["mineral-cream-dirt-4"] = "mineral-cream-dirt-4",
                ["mineral-cream-dirt-5"] = "mineral-cream-dirt-5",
                ["mineral-cream-dirt-6"] = "mineral-cream-dirt-6",
                ["mineral-cream-sand-1"] = "mineral-cream-sand-1",
                ["mineral-cream-sand-2"] = "mineral-cream-sand-2",
                ["mineral-cream-sand-3"] = "mineral-cream-sand-3",
                ["mineral-dustyrose-dirt-1"] = "mineral-dustyrose-dirt-1",
                ["mineral-dustyrose-dirt-2"] = "mineral-dustyrose-dirt-2",
                ["mineral-dustyrose-dirt-3"] = "mineral-dustyrose-dirt-3",
                ["mineral-dustyrose-dirt-4"] = "mineral-dustyrose-dirt-4",
                ["mineral-dustyrose-dirt-5"] = "mineral-dustyrose-dirt-5",
                ["mineral-dustyrose-dirt-6"] = "mineral-dustyrose-dirt-6",
                ["mineral-dustyrose-sand-1"] = "mineral-dustyrose-sand-1",
                ["mineral-dustyrose-sand-2"] = "mineral-dustyrose-sand-2",
                ["mineral-dustyrose-sand-3"] = "mineral-dustyrose-sand-3",
                ["mineral-grey-dirt-1"] = "mineral-grey-dirt-1",
                ["mineral-grey-dirt-2"] = "mineral-grey-dirt-2",
                ["mineral-grey-dirt-3"] = "mineral-grey-dirt-3",
                ["mineral-grey-dirt-4"] = "mineral-grey-dirt-4",
                ["mineral-grey-dirt-5"] = "mineral-grey-dirt-5",
                ["mineral-grey-dirt-6"] = "mineral-grey-dirt-6",
                ["mineral-grey-sand-1"] = "mineral-grey-sand-1",
                ["mineral-grey-sand-2"] = "mineral-grey-sand-2",
                ["mineral-grey-sand-3"] = "mineral-grey-sand-3",
                ["mineral-purple-dirt-1"] = "mineral-purple-dirt-1",
                ["mineral-purple-dirt-2"] = "mineral-purple-dirt-2",
                ["mineral-purple-dirt-3"] = "mineral-purple-dirt-3",
                ["mineral-purple-dirt-4"] = "mineral-purple-dirt-4",
                ["mineral-purple-dirt-5"] = "mineral-purple-dirt-5",
                ["mineral-purple-dirt-6"] = "mineral-purple-dirt-6",
                ["mineral-purple-sand-1"] = "mineral-purple-sand-1",
                ["mineral-purple-sand-2"] = "mineral-purple-sand-2",
                ["mineral-purple-sand-3"] = "mineral-purple-sand-3",
                ["mineral-red-dirt-1"] = "mineral-red-dirt-1",
                ["mineral-red-dirt-2"] = "mineral-red-dirt-2",
                ["mineral-red-dirt-3"] = "mineral-red-dirt-3",
                ["mineral-red-dirt-4"] = "mineral-red-dirt-4",
                ["mineral-red-dirt-5"] = "mineral-red-dirt-5",
                ["mineral-red-dirt-6"] = "mineral-red-dirt-6",
                ["mineral-red-sand-1"] = "mineral-red-sand-1",
                ["mineral-red-sand-2"] = "mineral-red-sand-2",
                ["mineral-red-sand-3"] = "mineral-red-sand-3",
                ["mineral-tan-dirt-1"] = "mineral-tan-dirt-1",
                ["mineral-tan-dirt-2"] = "mineral-tan-dirt-2",
                ["mineral-tan-dirt-3"] = "mineral-tan-dirt-3",
                ["mineral-tan-dirt-4"] = "mineral-tan-dirt-4",
                ["mineral-tan-dirt-5"] = "mineral-tan-dirt-5",
                ["mineral-tan-dirt-6"] = "mineral-tan-dirt-6",
                ["mineral-tan-sand-1"] = "mineral-tan-sand-1",
                ["mineral-tan-sand-2"] = "mineral-tan-sand-2",
                ["mineral-tan-sand-3"] = "mineral-tan-sand-3",
                ["mineral-violet-dirt-1"] = "mineral-violet-dirt-1",
                ["mineral-violet-dirt-2"] = "mineral-violet-dirt-2",
                ["mineral-violet-dirt-3"] = "mineral-violet-dirt-3",
                ["mineral-violet-dirt-4"] = "mineral-violet-dirt-4",
                ["mineral-violet-dirt-5"] = "mineral-violet-dirt-5",
                ["mineral-violet-dirt-6"] = "mineral-violet-dirt-6",
                ["mineral-violet-sand-1"] = "mineral-violet-sand-1",
                ["mineral-violet-sand-2"] = "mineral-violet-sand-2",
                ["mineral-violet-sand-3"] = "mineral-violet-sand-3",
                ["mineral-white-dirt-1"] = "mineral-white-dirt-1",
                ["mineral-white-dirt-2"] = "mineral-white-dirt-2",
                ["mineral-white-dirt-3"] = "mineral-white-dirt-3",
                ["mineral-white-dirt-4"] = "mineral-white-dirt-4",
                ["mineral-white-dirt-5"] = "mineral-white-dirt-5",
                ["mineral-white-dirt-6"] = "mineral-white-dirt-6",
                ["mineral-white-sand-1"] = "mineral-white-sand-1",
                ["mineral-white-sand-2"] = "mineral-white-sand-2",
                ["mineral-white-sand-3"] = "mineral-white-sand-3",
                ["vegetation-blue-grass-1"] = "vegetation-blue-grass-1",
                ["vegetation-blue-grass-2"] = "vegetation-blue-grass-2",
                ["vegetation-green-grass-1"] = "vegetation-green-grass-1",
                ["vegetation-green-grass-2"] = "vegetation-green-grass-2",
                ["vegetation-green-grass-3"] = "vegetation-green-grass-3",
                ["vegetation-green-grass-4"] = "vegetation-green-grass-4",
                ["vegetation-mauve-grass-1"] = "vegetation-mauve-grass-1",
                ["vegetation-mauve-grass-2"] = "vegetation-mauve-grass-2",
                ["vegetation-olive-grass-1"] = "vegetation-olive-grass-1",
                ["vegetation-olive-grass-2"] = "vegetation-olive-grass-2",
                ["vegetation-orange-grass-1"] = "vegetation-orange-grass-1",
                ["vegetation-orange-grass-2"] = "vegetation-orange-grass-2",
                ["vegetation-purple-grass-1"] = "vegetation-purple-grass-1",
                ["vegetation-purple-grass-2"] = "vegetation-purple-grass-2",
                ["vegetation-red-grass-1"] = "vegetation-red-grass-1",
                ["vegetation-red-grass-2"] = "vegetation-red-grass-2",
                ["vegetation-turquoise-grass-1"] = "vegetation-turquoise-grass-1",
                ["vegetation-turquoise-grass-2"] = "vegetation-turquoise-grass-2",
                ["vegetation-violet-grass-1"] = "vegetation-violet-grass-1",
                ["vegetation-violet-grass-2"] = "vegetation-violet-grass-2",
                ["vegetation-yellow-grass-1"] = "vegetation-yellow-grass-1",
                ["vegetation-yellow-grass-2"] = "vegetation-yellow-grass-2",
                ["water-mud"] = "water-mud",
                ["water-shallow"] = "water-shallow"
            }
        },
        ["tree-volcanic-a"] = {
            {
                red = "red",
                yellow = "yellow"
            },
            {
                ["volcanic-blue-heat-1"] = "volcanic-blue-heat-1",
                ["volcanic-green-heat-1"] = "volcanic-green-heat-1",
                ["volcanic-orange-heat-1"] = "volcanic-orange-heat-1",
                ["volcanic-purple-heat-1"] = "volcanic-purple-heat-1"
            }
        },
        ["tree-wetland-a"] = {
            {
                green = "green",
                yellow = "yellow"
            }
        },
        ["tree-wetland-b"] = {
            {
                orange = "orange",
                red = "red"
            }
        },
        ["tree-wetland-c"] = {
            {
                red = "red"
            }
        },
        ["tree-wetland-d"] = {
            {
                red = "red"
            }
        },
        ["tree-wetland-e"] = {
            {
                green = "green"
            }
        },
        ["tree-wetland-f"] = {
            {
                violet = "violet",
                white = "white"
            }
        },
        ["tree-wetland-g"] = {
            {
                yellow = "yellow"
            }
        },
        ["tree-wetland-h"] = {
            {
                purple = "purple"
            }
        },
        ["tree-wetland-i"] = {
            {
                green = "green"
            }
        },
        ["tree-wetland-j"] = {
            {
                blue = "blue",
                purple = "purple",
                turquoise = "turquoise"
            }
        },
        ["tree-wetland-k"] = {
            {
                purple = "purple",
                red = "red"
            }
        },
        ["tree-wetland-l"] = {
            {
                blue = "blue"
            }
        },
        ["tree-wetland-m"] = {
            {
                green = "green",
                turquoise = "turquoise"
            }
        },
        ["tree-wetland-n"] = {
            {
                green = "green",
                turquoise = "turquoise"
            }
        },
        ["tree-wetland-o"] = {
            {
                green = "green"
            }
        }
    }
end

Data.GetTileTagToTreeColors = function()
    --[[local tagsToColors = {
        purple = {violet = "violet", purple= "purple", red = "red"},
        red = {orange = "orange", red = "red", purple = "purple"},
        violet = {purple = "purple", violet = "violet", blue = "blue"},
        blue = {violet = "violet", blue = "blue", turquoise = "turquoise"},
        green = {turquoise = "turquoise", green = "green", yellow = "yellow"},
        orange = {yellow = "yellow", orange = "orange", red = "red"},
        turquoise = {blue = "blue", turquoise = "turquoise", green = "green"},
        yellow = {green = "green", yellow = "yellow", orange = "orange"}
    }]]
    local tagsToColors = {
        purple = {purple = "purple"},
        red = {red = "red"},
        violet = {violet = "violet"},
        blue = {blue = "blue"},
        green = {green = "green"},
        orange = {orange = "orange"},
        turquoise = {turquoise = "turquoise"},
        yellow = {yellow = "yellow"}
    }
    tagsToColors.mauve = tagsToColors.violet
    tagsToColors.olive = tagsToColors.green
    tagsToColors.white = {white = "white"}
    tagsToColors.aubergine = tagsToColors.purple
    tagsToColors.beige = tagsToColors.yellow
    tagsToColors.black = {white = "white"}
    tagsToColors.brown = tagsToColors.yellow
    tagsToColors.cream = tagsToColors.yellow
    tagsToColors.dustyrose = tagsToColors.red
    tagsToColors.grey = {white = "white"}
    tagsToColors.tan = tagsToColors.yellow
    --[[
        Tree Colors:
            violet
            purple
            blue
            turquoise
            green
            yellow
            orange - not a real tree color, just for volcanic it seems
            red
            white
    ]]
    return tagsToColors
end

return Data
