require("modes.halloween-2023.prototypes.maze")
require("modes.halloween-2023.prototypes.biter-eggs")
require("modes.halloween-2023.prototypes.zombie-engineer")
require("modes.halloween-2023.prototypes.combat-lighting")
require("modes.halloween-2023.prototypes.lamps")
